### ISSUE TITLE
Network error: Store reset while query was in flight(not completed in link chain)

### ISSUE THREAD

**Issue by alexvpickering** [aws-samples/aws-amplify-graphql#3]
Occurs after login. Photos don't show up in table despite being present under S3 bucket `photoclient-userfiles-mobilhub-*` --> `private` --> `us-east-*`.

If I sign in, then add a photo, then refresh the page, the entire table of photos shows up. A subsequent refresh and they all disappear with the below error.

Full error:

```console
Unhandled (in react-apollo:Apollo(AllPhotos)) Error: Network error: Store reset while query was in flight(not completed in link chain)
    at new ApolloError (http://localhost:3000/static/js/bundle.js:9201:28)
    at ObservableQuery../node_modules/apollo-client/core/ObservableQuery.js.ObservableQuery.currentResult (http://localhost:3000/static/js/bundle.js:7685:24)
    at GraphQL.dataForChild (http://localhost:3000/static/js/bundle.js:101196:62)
    at GraphQL.render (http://localhost:3000/static/js/bundle.js:101246:33)
    at finishClassComponent (http://localhost:3000/static/js/bundle.js:109766:31)
    at updateClassComponent (http://localhost:3000/static/js/bundle.js:109743:12)
    at beginWork (http://localhost:3000/static/js/bundle.js:110118:16)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:112117:16)
    at workLoop (http://localhost:3000/static/js/bundle.js:112181:26)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:102435:14)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:102474:16)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:102331:27)
    at renderRoot (http://localhost:3000/static/js/bundle.js:112259:7)
    at performWorkOnRoot (http://localhost:3000/static/js/bundle.js:112907:24)
    at performWork (http://localhost:3000/static/js/bundle.js:112860:7)
    at requestWork (http://localhost:3000/static/js/bundle.js:112771:7)
    at scheduleWorkImpl (http://localhost:3000/static/js/bundle.js:112625:11)
    at scheduleWork (http://localhost:3000/static/js/bundle.js:112582:12)
    at Object.enqueueForceUpdate (http://localhost:3000/static/js/bundle.js:108143:7)
    at GraphQL../node_modules/react/cjs/react.development.js.Component.forceUpdate (http://localhost:3000/static/js/bundle.js:123389:16)
    at GraphQL.forceRenderChildren (http://localhost:3000/static/js/bundle.js:101164:26)
    at next (http://localhost:3000/static/js/bundle.js:101139:27)
    at Object.handleError [as error] (http://localhost:3000/static/js/bundle.js:101143:32)
    at SubscriptionObserver.error (http://localhost:3000/static/js/bundle.js:162160:20)
    at http://localhost:3000/static/js/bundle.js:7924:82
    at Array.forEach (<anonymous>)
    at Object.error (http://localhost:3000/static/js/bundle.js:7924:33)
    at http://localhost:3000/static/js/bundle.js:8250:38
    at http://localhost:3000/static/js/bundle.js:8629:17
    at Array.forEach (<anonymous>)
    at http://localhost:3000/static/js/bundle.js:8628:18
    at Map.forEach (<anonymous>)
    at QueryManager../node_modules/apollo-client/core/QueryManager.js.QueryManager.broadcastQueries (http://localhost:3000/static/js/bundle.js:8623:22)
    at http://localhost:3000/static/js/bundle.js:8192:31
    at <anonymous>
__stack_frame_overlay_proxy_console__ @ index.js:2177
(anonymous) @ react-apollo.browser.umd.js:545
setTimeout (async)
GraphQL.dataForChild @ react-apollo.browser.umd.js:543
GraphQL.render @ react-apollo.browser.umd.js:590
finishClassComponent @ react-dom.development.js:7873
updateClassComponent @ react-dom.development.js:7850
beginWork @ react-dom.development.js:8225
performUnitOfWork @ react-dom.development.js:10224
workLoop @ react-dom.development.js:10288
callCallback @ react-dom.development.js:542
invokeGuardedCallbackDev @ react-dom.development.js:581
invokeGuardedCallback @ react-dom.development.js:438
renderRoot @ react-dom.development.js:10366
performWorkOnRoot @ react-dom.development.js:11014
performWork @ react-dom.development.js:10967
requestWork @ react-dom.development.js:10878
scheduleWorkImpl @ react-dom.development.js:10732
scheduleWork @ react-dom.development.js:10689
enqueueForceUpdate @ react-dom.development.js:6250
./node_modules/react/cjs/react.development.js.Component.forceUpdate @ react.development.js:255
GraphQL.forceRenderChildren @ react-apollo.browser.umd.js:508
next @ react-apollo.browser.umd.js:483
handleError @ react-apollo.browser.umd.js:487
error @ zen-observable.js:178
(anonymous) @ ObservableQuery.js:326
error @ ObservableQuery.js:326
(anonymous) @ QueryManager.js:280
(anonymous) @ QueryManager.js:659
(anonymous) @ QueryManager.js:658
./node_modules/apollo-client/core/QueryManager.js.QueryManager.broadcastQueries @ QueryManager.js:653
(anonymous) @ QueryManager.js:222
Promise rejected (async)
./node_modules/apollo-client/core/QueryManager.js.QueryManager.fetchQuery @ QueryManager.js:213
./node_modules/apollo-client/core/QueryManager.js.QueryManager.startQuery @ QueryManager.js:556
./node_modules/apollo-client/core/ObservableQuery.js.ObservableQuery.setUpQuery @ ObservableQuery.js:329
./node_modules/apollo-client/core/ObservableQuery.js.ObservableQuery.onSubscribe @ ObservableQuery.js:298
(anonymous) @ ObservableQuery.js:37
Subscription @ zen-observable.js:110
subscribe @ zen-observable.js:233
GraphQL.subscribeToQuery @ react-apollo.browser.umd.js:490
GraphQL.componentDidMount @ react-apollo.browser.umd.js:268
commitLifeCycles @ react-dom.development.js:8770
commitAllLifeCycles @ react-dom.development.js:9946
callCallback @ react-dom.development.js:542
invokeGuardedCallbackDev @ react-dom.development.js:581
invokeGuardedCallback @ react-dom.development.js:438
commitRoot @ react-dom.development.js:10050
performWorkOnRoot @ react-dom.development.js:11017
performWork @ react-dom.development.js:10967
requestWork @ react-dom.development.js:10878
scheduleWorkImpl @ react-dom.development.js:10732
scheduleWork @ react-dom.development.js:10689
enqueueSetState @ react-dom.development.js:6212
./node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:237
handleAuthStateChange @ index.js:238
handleStateChange @ Authenticator.js:122
changeState @ AuthPiece.js:119
(anonymous) @ Greetings.js:119
Promise resolved (async)
checkUser @ Greetings.js:110
componentDidMount @ Greetings.js:72
commitLifeCycles @ react-dom.development.js:8770
commitAllLifeCycles @ react-dom.development.js:9946
callCallback @ react-dom.development.js:542
invokeGuardedCallbackDev @ react-dom.development.js:581
invokeGuardedCallback @ react-dom.development.js:438
commitRoot @ react-dom.development.js:10050
performWorkOnRoot @ react-dom.development.js:11017
performWork @ react-dom.development.js:10967
requestWork @ react-dom.development.js:10878
scheduleWorkImpl @ react-dom.development.js:10732
scheduleWork @ react-dom.development.js:10689
enqueueSetState @ react-dom.development.js:6212
./node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:237
(anonymous) @ rehydrated.js:76
step @ rehydrated.js:42
(anonymous) @ rehydrated.js:23
fulfilled @ rehydrated.js:14
Promise resolved (async)
step @ rehydrated.js:16
(anonymous) @ rehydrated.js:17
./node_modules/aws-appsync-react/lib/rehydrated.js.__awaiter @ rehydrated.js:13
./node_modules/aws-appsync-react/lib/rehydrated.js.Rehydrated.componentWillMount @ rehydrated.js:70
callComponentWillMount @ react-dom.development.js:6370
mountClassInstance @ react-dom.development.js:6435
updateClassComponent @ react-dom.development.js:7840
beginWork @ react-dom.development.js:8225
performUnitOfWork @ react-dom.development.js:10224
workLoop @ react-dom.development.js:10288
callCallback @ react-dom.development.js:542
invokeGuardedCallbackDev @ react-dom.development.js:581
invokeGuardedCallback @ react-dom.development.js:438
renderRoot @ react-dom.development.js:10366
performWorkOnRoot @ react-dom.development.js:11014
performWork @ react-dom.development.js:10967
requestWork @ react-dom.development.js:10878
scheduleWorkImpl @ react-dom.development.js:10732
scheduleWork @ react-dom.development.js:10689
scheduleTopLevelUpdate @ react-dom.development.js:11193
updateContainer @ react-dom.development.js:11231
(anonymous) @ react-dom.development.js:15226
unbatchedUpdates @ react-dom.development.js:11102
renderSubtreeIntoContainer @ react-dom.development.js:15225
render @ react-dom.development.js:15290
./src/index.js @ index.js:7
__webpack_require__ @ bootstrap 0b1d28e6609e8bf1486c:678
fn @ bootstrap 0b1d28e6609e8bf1486c:88
2 @ lib fs:1
__webpack_require__ @ bootstrap 0b1d28e6609e8bf1486c:678
./node_modules/@redux-offline/redux-offline/lib/actions.js.Object.defineProperty.value @ bootstrap 0b1d28e6609e8bf1486c:724
(anonymous) @ bootstrap 0b1d28e6609e8bf1486c:724
```

**Comment by elorzafe** [comment]
Hi @alexvpickering which version of awsmobile-cli are you using?

**Comment by elorzafe** [comment]
I have uploaded a yarn.lock file under photo-client directory, can you try running **yarn** to update the dependencies?

Thanks

**Comment by alexvpickering** [comment]
Thank you @elorzafe

Tried again with the updated yarn.lock and works. Adding `<ExposeHeader>ETag</ExposeHeader>` to the `photoclient-userfiles-mobilehub-*` S3 bucket  was still required. Should probably be mentioned in the README.

**Comment by elorzafe** [comment]
Nice,

This is mine CORS configuration on the S3 bucket after creating enabling and pushing using awsmobile-cli
```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>HEAD</AllowedMethod>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>DELETE</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <ExposeHeader>x-amz-server-side-encryption</ExposeHeader>
    <ExposeHeader>x-amz-request-id</ExposeHeader>
    <ExposeHeader>x-amz-id-2</ExposeHeader>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```

I dont have the tag you mention and is working correctly. Con you try with this configuration?

**Comment by alexvpickering** [comment]
Just tried again.

App signs in but when I try to add another photo I get the `Check CORS configuration to expose ETag header.` error with the above config.

**Comment by elorzafe** [comment]
Is very strange, can you paste the contents under ```photo-client/awsmobilejs/backend/mobile-hub-project.yml```

it should be something like this
```
186590d38aef:backend elorzafe$ cat mobile-hub-project.yml
--- !com.amazonaws.mobilehub.v0.Project
features:
  content-delivery: !com.amazonaws.mobilehub.v0.ContentDelivery
    attributes:
      enabled: true
      visibility: public-global
    components:
      release: !com.amazonaws.mobilehub.v0.Bucket {}
  mobile-analytics: !com.amazonaws.mobilehub.v0.Pinpoint
    components:
      analytics: !com.amazonaws.mobilehub.v0.PinpointAnalytics {}
  sign-in: !com.amazonaws.mobilehub.v0.SignIn
    attributes:
      enabled: true
      optional-sign-in: true
    components:
      sign-in-user-pools: !com.amazonaws.mobilehub.v0.UserPoolsIdentityProvider
        attributes:
          alias-attributes:
            - email
            - phone_number
          mfa-configuration: ON
          name: userpool
          password-policy: !com.amazonaws.mobilehub.ConvertibleMap
            min-length: '8'
            require-lower-case: true
            require-numbers: true
            require-symbols: true
            require-upper-case: true
  user-files: !com.amazonaws.mobilehub.v0.UserFiles
    attributes:
      enabled: true
      wildcard-cors-policy: true
name: photo-client-2018-03-16-10-00-06
region: us-east-1
```

Under **user-files** it should have ```wildcard-cors-policy: true```
